### ISSUE TITLE
Redaxo Version vor Version 5

### ISSUE THREAD

**Issue by HashDot** [FriendsOfREDAXO/redaxo-mit-docker#10]
Hi,

danke für das tolle Paket mit Docker und Redaxo. Das erspart eine menge Arbeit für eine Dev Umgebung. Leider ist es so das man aktuell nur Redaxo 5+ verwenden kann. Ich habe versucht eine Redaxo 4.7.2 Installation damit zu machen aber es scheitert daran wie die Sources, etc. von Redaxo 4 angeboten werden. Es ist ein anderes "Schema" als für Redaxo 5. Also die Links, Checksums etc.

Ist es möglich es soweit anzupassen damit man damit auf Redaxo 4.x.x damit zum laufen bekommt?

**Comment by staabm** [comment]
ich habs noch nie benutzt, aber vermutlich kann man hier die version einstellen, oder?

https://github.com/FriendsOfREDAXO/redaxo-mit-docker/blob/0dd1ea073810fee4b9421db623f0e9d59d31480b/docker/php-apache/Dockerfile#L22-L27

**Comment by schuer** [comment]
Hey @HashDot, danke für dein Feedback!
REDAXO 4 ist in dem Setup grundsätzlich lauffähig, allerdings wird die automatische Installation nicht funktionieren. Die verwendet nämlich durchweg R5-Features. Man müsste mindestens die [docker-redaxo.php](https://github.com/FriendsOfREDAXO/redaxo-mit-docker/blob/master/docker/php-apache/docker-redaxo.php) für R4 umschreiben, wobei ich gar nicht weiß, ob alle benötigten Features überhaupt in R4 vorhanden sind. Es werden einige Funktionen des Installer-AddOns verwendet.

Ich benutze das Docker-Setup für R4 nur als Serverumgebung und installiere mir REDAXO manuell dazu bzw. werfe meine vorhandenen R4-Projekte in den html-Folder und importiere die Datenbank. Statt MAMP oder sowas also Docker.
Zu beachten ist dabei noch, dass ältere R4s nicht mit PHP 7 klarkommen, sondern PHP 5 mit etwas anderen Extensions (mysqli, glaube ich) benötigen. R 4.7 funktioniert allerdings auch mit PHP 7.

Hilft dir die Info so weiter?

**Comment by HashDot** [comment]
@schuer, danke für die ausführliche Erklärung. Das Docker Setup als Basis zu nehmen passt für mich.

**Comment by schuer** [comment]
Gerne! Für REX <4.7 mit PHP 5.6 sieht mein Dockerfile übrigens so aus:

```sh
FROM php:5.6-apache

# copy custom configs
COPY php.ini /usr/local/etc/php/
COPY apache.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod expires headers rewrite ssl

# install extensions
RUN apt-get update -q && apt-get install -qy \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd mysql
```

**Comment by HashDot** [comment]
Ich habe gestern probiert Redaxo 4.7.2 mit deiner Dockerfile zu starten und auch mit der "originalen" Dockerfile. Leider taucht immer wieder folgender Fehler auf:

`PHP Fatal error:  php7-mysql-shim: ext/mysqli is required in /var/www/html/redaxo/include/functions/php7-mysql-shim/mysql.php on line 25`

Habe auch schon versucht die Dockerfile anzupassen das entsprechend die fehlende Abhängigkeit installiert wird. Leider ohne Erfolg. Hast du eine Idee @schuer ?

**Comment by schuer** [comment]
Okay stimmt, REX 4.7 benötigt mysqli, ältere REX-Versionen nicht. Kannst du sehr einfach ergänzen in der letzten Zeile des Snippets:

```sh
   && docker-php-ext-install -j$(nproc) gd mysql mysqli
```

Neu zu bauen nicht vergessen danach: `docker-compose up -d --build --force-recreate`.

**Comment by HashDot** [comment]
Funktioniert. Danke für die schnelle Antwort!
