### ISSUE TITLE
Implement Xdebug

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/redaxo-mit-docker#18]
Xdebug — Step Debugger and Debugging Aid for PHP
https://xdebug.org

**Comment by staabm** [comment]
blackfire und xdebug zugleich sollte man nicht laufen haben, da dies die ermittelten zahlen von blackfire verfälscht.

wenn du beides willst, müsstest du einen mechanismus schaffen wie man zwischen den extensions wechseln soll/kann

**Comment by schuer** [comment]
Gute zu wissen, danke für die Info! Gregor meinte schon im Slack, dass xdebug an- und abschaltbar sein sollte. Abschalten würde reichen für Blackfire, oder darf es gar nicht installiert sein?

**Comment by staabm** [comment]
xdebug macht eine php instanz langsam sobald es nur geladen ist. egal ob via php-ini aktiviert oder nicht, d.h. ein ab/ausschalten aus user sicht, muss ein komplettes "nicht-laden" von xdebug in den php-prozess bedeuten.

**Comment by schuer** [comment]
Alles klar, danke!

**Comment by schuer** [comment]
Benutzt man eigentlich Xdebug im REDAXO-Umfeld oder besteht wenig Bedarf? Sonst würde ich hier eher schließen wollen.

**Comment by schuer** [comment]
Kein Bedarf für Xdebug, deshalb schließe ich mal hier.
