### ISSUE TITLE
Setup Optionen

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/redaxo-mit-docker#23]
Es wäre schön wenn man das Repository auch dazu einsetzen könnte eine Entwicklungsumgebung aufzusetzen. Man könnte ein Setup Shellscript anlegen mit dem es möglich ist die Container-Namen und -Ports zu setzen.

**Comment by schuer** [comment]
Entschuldige Joachim, dieses Issue ist während meines Urlaubs angelegt worden, und ich habe es komplett verpasst. Lese es gerade erst.

Ich bin mir gerade nicht sicher, ob so ein Setup-Script notwendig und sinnvoll ist. Es macht diese recht komplexe Sache noch komplexer, und eigentlich soll das Projekt hier ja nur eine funktionsfähige Anleitung sein, die zwar als Produktionsumgebung taugt, die aber nicht die eine finale Lösung für alle sein soll, sondern sicherlich an diversen Stellen individualisiert wird von den Nutzern.

Falls du so ein Setup-Script schon entwickelt hast, magst du es vielleicht mal vorstellen? Dann können wir ja diskutieren, ob wir es mit drin haben wollen, oder ob es lieber irgendwo anders abgelegt und von hier nur verlinkt wird.

**Comment by joachimdoerr** [comment]
Hello Dirk, kein Problem ich komme auch nicht immer sofort dazu die Issues anzuschauen und zu jedem etwas konstruktives von mir abzugeben.
Ich denke es wäre sinnvoll ggf. auch als subproject sowas aufzusetzen. Ich hab jedesmal das Problem, dass ich diese Anpassungen von Hand durchführe wenn ich ein Redaxo brauche. Von daher dachte ich erstmal an ein kleines Shellscript mit dem man sowas einfach umsetzen könnte. So ein Script kann man ja auch unabhängig aufbauen es muss nicht zwingend in das Repo.
