### ISSUE TITLE
Linux: Internal server error "Clang cache file could not be generated"

### ISSUE THREAD

**Issue by dundunn** [FriendsOfREDAXO/redaxo-mit-docker#25]
Unter Windows hatte ich keine Probleme, dieses Projekt zu starten. Ich clone das Repo, führe "docker-compose up -d" aus und kann unter localhost:20080 die Demo ansehen. 
Wenn ich dasselbe in einer Linux-Distribution versuche zeigt der Browser "Oooops, an internal error occured!" an. Mit debug wird mir folgendes angezeigt:
```
rex_exception thrown with message "Clang cache file could not be generated"

Stacktrace:
#5 rex_exception in /var/www/html/redaxo/src/core/lib/clang/service.php:144
#4 rex_clang_service:generateCache in /var/www/html/redaxo/src/core/lib/clang/clang.php:238
#3 rex_clang:checkCache in /var/www/html/redaxo/src/core/lib/clang/clang.php:216
#2 rex_clang:getAll in /var/www/html/redaxo/src/core/lib/clang/clang.php:61
#1 rex_clang:getStartId in /var/www/html/redaxo/src/core/boot.php:117
#0 require in /var/www/html/redaxo/index.php:9
```

Ausgeführt wurde es auf meinem lokalen Computer unter Arch Linux. Auf demselben Computer läuft auch das Windows, mit dem ich keine Probleme hatte.
Um sicher zu gehen, dass es nicht an irgendeiner Konfiguration oder an den Packages von Arch liegt, habe ich Ubuntu 18.04 in VirtualBox aufgesetzt und dort getestet. Es passiert genau dasselbe wie auch in Arch.

**Comment by schuer** [comment]
Ich habe hier leider keine Umgebung, um das Problem zu testen. Evtl fehlen Schreibrechte für den Cache-Folder? Hast du mal versucht, das REDAXO-Setup durchlaufen zu lassen bzw REDAXO manuell in einem leeren Container zu installieren, damit man sieht, ob es fehlerfrei durchläuft oder über irgendwas meckert?

**Comment by dundunn** [comment]
Sorry für die späte Rückmeldung, ich hatte Urlaub und das Problem ganz vergessen. 

Ich habe nun diese Zeilen entfernt und probiert die Installation manuell durchzuführen. https://github.com/FriendsOfREDAXO/redaxo-mit-docker/blob/e982f612d9ca2200134e8b2db987d3d3ed74ac10/docker/php-apache/Dockerfile#L27-L49

Bei der Installation kann ich mich nicht mit der Datenbank verbinden (`Es konnte keine Verbindung zur Datenbank hergestellt werden!`). Ich verwende localhost:3306 für Host und redaxo für Datenbank, User und Passwort. Die Datenbank ist aber definitiv an und erreichbar. Ich kann mich problemlos mit MySQL-Workbench mit der Datenbank als User redaxo verbinden und Änderungen vornehmen. 

Gibt es eine Möglichkeit den Debug-Modus während der Installation einzuschalten?

**Comment by schuer** [comment]
Hey @dundunn, inzwischen gibt es [REDAXO-Images im Docker Hub](https://hub.docker.com/r/friendsofredaxo/redaxo), die nun auch hier im Projekt verwendet werden.

Ich vermute stark, dass sich dieses Issue damit erledigt hat, und schließe deshalb. Falls das Problem aber nachwievor besteht, öffne gerne wieder!
