### ISSUE TITLE
Update to REDAXO 5.8.1

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/redaxo-mit-docker#31]
Can be done here:

https://github.com/FriendsOfREDAXO/redaxo-mit-docker/blob/051db205432de159f19d21c5ea67bac6992c370c/docker/php-apache/Dockerfile#L35-L37

**Comment by skerbis** [comment]
done: https://github.com/FriendsOfREDAXO/redaxo-mit-docker/pull/32
