### ISSUE TITLE
Cache-löschen-Button löscht Addon-Cache nicht

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/redaxo-mit-docker#35]
Der Cache-Löschen-Button unter System löscht den Addon-Cache nicht (auch den Core-Cache nicht, aber evtl. ist das so gewollt). 
In meinem Fall wird der Cache unter `/redaxo/cache/addons/yform/plugins/manager/tables.cache` nicht neu generiert. 
Denke das liegt an Docker / Dateirechten, ich meine dass das ausserhalb von Docker funktioniert (kann mich aber täuschen, nicht getestet)

REDAXO: 5.9.0 und 5.10.0
PHP: 7.3.13

Original-Issue hier: https://github.com/redaxo/redaxo/issues/3452

**Comment by bloep** [comment]
Ist das Verhalten nur bei dem Ordner?

Ich vermute, dass der Ordner bzw. Dateien in dem Ordner andere Berechtigungen haben als die andern Ordner im Cache. Kannst du das bestätigen?

Am Rande, auf welchen Betriebsystem verwendest du Docker? Ich hatte mal bei der nativen Linux Variante nen ähnliches verhalten.

@schuer du bist vermutlich tiefer in der Docker thematik drin als ich 😉

**Comment by ynamite** [comment]
> Ist das Verhalten nur bei dem Ordner?

Scheint zumindest so. Konkret wurde die Datei tables.cache nicht neu generiert bzw. lieferte mir im Backend nicht (mehr) existierende Werte. Den Timestamp hab ich aber gar nicht überprüft, kann auch sein, dass sie neu generiert wurde aber trotzdem nicht gefunzt hat. Denke aber sie konnte gar nicht erst neu generiert werden. Nachdem ich die tables.cache manuell gelöscht hatte und nochmals frisch generieren liess, hat's dann geklappt.

> Ich vermute, dass der Ordner bzw. Dateien in dem Ordner andere Berechtigungen haben als die andern Ordner im Cache. Kannst du das bestätigen?

Komischerweise nicht, scheinbar dieselben wie alle anderen Dateien: -rw-rw-r--
Ordner: drwxrwxr-x 

> Am Rande, auf welchen Betriebsystem verwendest du Docker? Ich hatte mal bei der nativen Linux Variante nen ähnliches verhalten.

Mac OS v10.15.3

Schreibt Redaxo etwas ins Log wenn eine Cache Datei nicht gelöscht bzw. neu generiert werden kann? Also stehen tut da nix.

Vielen Dank für die Hilfe!

**Comment by schuer** [comment]
Hi @ynamite, sorry, es hat ein Weilchen gedauert. Gestern wurden neue Images im Hub publiziert, die einen kleinen [Hotfix](FriendsOfREDAXO/docker-redaxo#23) bzgl. der File Owner/Groups mitbringen (`www-data` statt `root`), und das könnte dein Problem lösen. Denn vor allem der Cache-Folder war vorm Hotfix betroffen.

Bei bestehenden Installation wird der Hotfix allerdings nicht helfen, da müsstest du einmal manuell korrigieren:

    $ docker-compose exec redaxo /bin/bash
    $ chown -R www-data:www-data ./

Danach am besten mal in den Cache-Folder wechseln und mittels `ls -la` schauen, ob alle Ordner nun wirklich `www-data/www-data` haben.

**Comment by schuer** [comment]
Ich schließe hier mal. Falls der Fehler weiterhin auftaucht, gerne wieder öffnen! @ynamite
