### ISSUE TITLE
Bei der Installation wird kein Startartikel angelegt..

### ISSUE THREAD

**Issue by Pazekal90** [FriendsOfREDAXO/redaxo-mit-docker#37]
.. Was beim Öffnen der Seite zum ersten Mal direkt auf eine "OOOPS" Seite leitet. Für ein besseres "erstes Gefühl" mit Redaxo sollte ein erster Artikel bspw. mit einer Startseite mit Redaxo Logo und den wichtigsten Links direkt angelegt werden. 

Denn auch im Admin beim Speichern von Einstellungen wird man immer erst darauf hingewiesen, dass noch kein Startartikel angelegt ist, man muss sich aber erst einmal zurecht finden, dass man weiß, dass dieser unter "Struktur" angelegt werden kann und dann der erste als Standard gewählt wird. 

Installation habe ich über den Docker Hub gemacht, ohne hier auf die Docker Compose zurückzugreifen.

**Comment by Pazekal90** [comment]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/25208775/83067805-9465da00-a067-11ea-943f-97f5e9964f1a.png">

**Comment by Pazekal90** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/25208775/83067875-af384e80-a067-11ea-8e9a-0f6831dd18d1.png">

**Comment by schuer** [comment]
@Pazekal90 Danke für deine Rückmeldung!

> Installation habe ich über den Docker Hub gemacht, ohne hier auf die Docker Compose zurückzugreifen.

Du hast dann vermutlich `friendsofredaxo/redaxo:5` als Image verwendet. Das ist in der Tat ein leeres REDAXO. Probiere lieber eine der Demos aus, etwa `friendsofredaxo/demo:base`, dann erhälst du eine komplette REDAXO-Website.

Eine gute Übersicht aller REDAXO-Images kriegst du hier: https://redaxo.org/download/demos/

**Comment by Pazekal90** [comment]
Ja das war mir bewusst :) Dann sind eure Bilder im Docker Hub an der Stelle aber verwirrend https://hub.docker.com/r/friendsofredaxo/redaxo. Hier wäre es gut wenn ihr das dazu schreibt, dass das ein leeres Template ist und ihr dann auf die Demos verweist. Denn sonst denken die Leute sie bekommen das hier wenn sie es installiert haben. 

<img width="839" alt="image" src="https://user-images.githubusercontent.com/25208775/83068504-be6bcc00-a068-11ea-96eb-4c76d3314296.png">

**Comment by schuer** [comment]
Guter Hinweis! Ich werde mal schauen, ob wir nicht einen passenderen Screenshot fürs REDAXO-Image bekommen.

**Comment by schuer** [comment]
Screenshot behalten wir vorerst bei, denn es ist der gleiche, den auch REDAXO verwendet, siehe https://github.com/redaxo/redaxo/

Info, dass REDAXO nach der Installation leer ist, und dass es Website-Demos gibt, wurde als PR angelegt und schließt dieses Issue, sobald er gemerged wird.

Danke für dein Feedback!
