### ISSUE TITLE
Redaxo Docker Image ist sehr groß

### ISSUE THREAD

**Issue by Pazekal90** [FriendsOfREDAXO/redaxo-mit-docker#38]
Mir ist aufgefallen, dass das Docker Hub Image vom Redaxo 5 sehr groß ist mit 500MB. Ich würde vermuten, dass in dem Docker Image eigentlich nur der Webserver und die Anwendung drin sind, da der DB Server nur per Compose hinzugeladen werden kann und nicht im Image direkt enthalten ist. 

Lässt sich das irgendwie reduzieren?

<img width="818" alt="image" src="https://user-images.githubusercontent.com/25208775/83178059-4f51ae80-a120-11ea-89b3-daf626f6bc11.png">

**Comment by schuer** [comment]
Laut Docker Hub sind die Images komprimiert nicht ungewöhnlich groß. Die [Apache-Variante](https://hub.docker.com/r/friendsofredaxo/redaxo/tags?page=1&name=apache) etwa 170 MB, die schmale [Alpine-Variante](https://hub.docker.com/r/friendsofredaxo/redaxo/tags?page=1&name=alpine) knapp 80. Damit sind sie sehr ähnlich groß wie beispielsweise WordPress oder Drupal im Hub.

**Comment by schuer** [comment]
Ich schließe hier, denn ich sehe aktuell keine Möglichkeit, die Images kleiner zu kriegen. Sie halten sich ziemlich gut an Best Practices, die beispielsweise in den offiziellen Images von WordPress und Drupal vorgegeben werden. Diese werden von Docker betreut, und ich gehe davon aus, dass sie wissen, was gut ist. ;)
