### ISSUE TITLE
SSL Test Zerfikatserstellung schlägt fehl

### ISSUE THREAD

**Issue by mherrm** [FriendsOfREDAXO/redaxo-mit-docker#39]
Bei der Ausführung des Kommandos "docker-compose up -d" erscheint der folgenden Fehler:

Service 'redaxo' failed to build: The command '/bin/sh -c openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj "/CN=localhost"' returned a non-zero code: 1

**Comment by schuer** [comment]
Hi @mherrm, ist es eine ganze frische Installation, oder hattest du REDAXO mit Docker schon vorher (womöglich in anderer Form) auf dem System? Und hast du irgendwas angepasst, oder nutzt du den Code so, wie er im Master-Branch des Repos enthalten ist?

Ich würde provisorisch mal folgendes tun:

    $ docker-compose down
    $ docker-compose pull
    $ docker pull friendsofredaxo/redaxo:5
    $ docker-compose up -d

Damit werden deine aktuellen Container gestoppt und verworfen (obwohl sie ja eigentlich noch gar nicht gestartet sind, aber egal), dann werden alle Images frisch aus dem Docker Hub geholt, sofern Updates vorhanden sind. Anschließend wird explizit das REDAXO-Image frisch geholt. Und am Ende wird neu gestartet.

**Comment by schuer** [comment]
Ich schließe hier mal. Falls der Fehler weiterhin auftaucht, gerne wieder öffnen! @mherrm
