### ISSUE TITLE
blackfire v1 is deprecated

### ISSUE THREAD

**Issue by ceekay82** [FriendsOfREDAXO/redaxo-mit-docker#41]
Erhalte im blackfire container folgende Nachricht:

Deprecation notice:
>blackfire v1 is deprecated and will sunset on September 1st, 2021. Consider upgrading to v2 soon.
>Read more: https://blackfire.io/docs/up-and-running/agent-upgrade

**Comment by schuer** [comment]
Danke für den Hinweis!

Als Ergänzung noch für die Person, die sich das Thema annimmt: In den Docs für Blackfire Probe steht noch v1. Abgesehen davon scheint sich nichts geändert zu haben. https://blackfire.io/docs/php/integrations/php-docker
