### ISSUE TITLE
Apple silicon:  mailhog Error  :: missing manifest

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/redaxo-mit-docker#44]
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by schuer** [comment]
Mailhog wurde leider seit ~2 Jahren nicht mehr aktualisiert und es fehlt offenbar eine Version für M1. Man könnte entweder einen geeigneten Fork suchen oder aber den Container emuliert laufen lassen, siehe etwa https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

Ich lasse das Issue offen zur Info für Mitlesende.

**Comment by skerbis** [comment]
Eine andere Alternative könnte Mailcatcher sein oder die in REDAXO integrierte Lösung

**Comment by schuer** [comment]
Eine gute Alternative ist Mailpit: https://github.com/axllent/mailpit. Funktioniert genauso, lässt sich quasi nahtlos tauschen.
