### ISSUE TITLE
Mysql container not starting due to change in mysql 8.4

### ISSUE THREAD

**Issue by rotegras** [FriendsOfREDAXO/redaxo-mit-docker#45]
**Description / Beschreibung**
In mysql 8.4 he "MySQL Native Password" plugin is no longer enabled by default. The mysql container fails to start.

**Affected versions / Verwendete Versionen**
mysql:8 pointing to mysql 8.4

For me the solution was to change in docker-compose.yml:

command: --default-authentication-plugin=mysql_native_password

to

command: ["mysqld", "--mysql-native-password=ON"]

**Comment by schuer** [comment]
Hey @rotegras, thanks for the hint! I’m currently not very deep into the topic, but maybe we can completely remove the usage of the default authentication plugin. As far as I remember, we had to use it at the beginning of MySQL 8.0.x for compatibility reasons?

**Comment by ReneCode** [comment]
I've created a PR. #46  that does the same

**Comment by schuer** [comment]
Fixed with #46
